

const mongoose = require('mongoose');
const Product = require('../models/Product');
require('dotenv').config();
 
const products = [
 
  {
    name: 'Logitech MK235 Wireless Keyboard & Mouse Combo',
    brand: 'Logitech',
    price: 1299,
    category: 'pc',
    rating: 4.3,
    reviews: 28470,
    description: 'Reliable wireless combo with 2.4 GHz connectivity and 12-month battery life.',
    features: ['Wireless 2.4GHz', 'Plug & Play', '12-month battery', 'Spill-resistant'],
    image: 'https://loremflickr.com/400/400/keyboard,mouse,logitech?lock=1',
  },
  {
    name: 'HP X1500 Wired USB Mouse',
    brand: 'HP',
    price: 499,
    category: 'pc',
    rating: 4.2,
    reviews: 56210,
    description: 'Comfortable ambidextrous mouse with 1000 DPI sensor.',
    features: ['1000 DPI', 'USB plug & play', 'Ambidextrous', '1.5m cable'],
    image: 'https://loremflickr.com/400/400/computer,mouse,usb?lock=2',
  },
  {
    name: 'Cosmic Byte CB-GK-19 Wired Keyboard',
    brand: 'Cosmic Byte',
    price: 1499,
    category: 'pc',
    rating: 4.4,
    reviews: 18230,
    description: 'Full-size keyboard with rainbow LED backlighting and multimedia keys.',
    features: ['Rainbow LED', 'Multimedia keys', 'Anti-ghosting', 'Gold-plated USB'],
    image: 'https://loremflickr.com/400/400/keyboard,rgb,gaming?lock=3',
  },
  {
    name: 'HP 22es 21.5-inch FHD Monitor',
    brand: 'HP',
    price: 9999,
    category: 'pc',
    rating: 4.5,
    reviews: 34210,
    description: 'Full HD IPS monitor with ultra-slim design and flicker-free display.',
    features: ['1920x1080 FHD', 'IPS Panel', 'Anti-glare', 'HDMI + VGA'],
    image: 'https://loremflickr.com/400/400/computer,monitor,screen?lock=4',
  },
  {
    name: 'Zebronics Zeb-Rush Stereo Headphones',
    brand: 'Zebronics',
    price: 799,
    category: 'pc',
    rating: 4.1,
    reviews: 45210,
    description: 'Over-ear headphones with HD sound and built-in microphone.',
    features: ['HD sound', 'Built-in mic', 'Foldable design', '3.5mm jack'],
    image: 'https://loremflickr.com/400/400/headphones,audio,earphones?lock=5',
  },
  {
    name: 'SanDisk Cruzer Blade 32GB Pendrive',
    brand: 'SanDisk',
    price: 399,
    category: 'pc',
    rating: 4.6,
    reviews: 89210,
    description: 'Compact and reliable USB 2.0 flash drive for everyday storage.',
    features: ['32GB storage', 'USB 2.0', 'Compact design', 'Password protection'],
    image: 'https://loremflickr.com/400/400/usb,flash,drive,storage?lock=6',
  },
  {
    name: 'Portronics Mport 7 USB Hub',
    brand: 'Portronics',
    price: 999,
    category: 'pc',
    rating: 4.2,
    reviews: 12340,
    description: '7-port USB 2.0 hub with individual LED indicators and power adapter.',
    features: ['7 USB ports', 'LED indicators', 'Power adapter', 'Plug & Play'],
    image: 'https://loremflickr.com/400/400/usb,hub,ports,technology?lock=7',
  },
  {
    name: 'WD Elements 1TB External Hard Drive',
    brand: 'Western Digital',
    price: 3299,
    category: 'pc',
    rating: 4.7,
    reviews: 62310,
    description: 'Portable 1TB storage with USB 3.0 for fast data transfers.',
    features: ['1TB storage', 'USB 3.0', 'Plug & Play', 'Auto backup'],
    image: 'https://loremflickr.com/400/400/hard,drive,storage,external?lock=8',
  },
  {
    name: 'TP-Link TL-WN823N USB WiFi Adapter',
    brand: 'TP-Link',
    price: 599,
    category: 'pc',
    rating: 4.1,
    reviews: 34210,
    description: '300Mbps wireless USB adapter, plug and play for desktop or laptop.',
    features: ['300Mbps', 'USB 2.0', 'Mini size', 'WPA/WPA2 security'],
    image: 'https://loremflickr.com/400/400/wifi,adapter,wireless,network?lock=9',
  },
  {
    name: 'HP DeskJet 2331 All-in-One Printer',
    brand: 'HP',
    price: 4999,
    category: 'pc',
    rating: 4.3,
    reviews: 23410,
    description: 'Compact all-in-one printer with print, scan, and copy functionality.',
    features: ['Print/Scan/Copy', 'USB connectivity', '1000 pages/month', 'Compact size'],
    image: 'https://loremflickr.com/400/400/printer,hp,office?lock=10',
  },
 
  // ─── GAMING SETUP ────────────────────────────────────────────
  {
    name: 'Ant Esports GM300W Optical Gaming Mouse',
    brand: 'Ant Esports',
    price: 999,
    category: 'gaming',
    rating: 4.3,
    reviews: 34210,
    description: 'Optical gaming mouse with 7 programmable buttons and RGB lighting.',
    features: ['7200 DPI', 'RGB lighting', '7 buttons', 'Braided cable'],
    image: 'https://loremflickr.com/400/400/gaming,mouse,rgb?lock=11',
  },
  {
    name: 'Redgear A-10 7.1 USB Gaming Headset',
    brand: 'Redgear',
    price: 1299,
    category: 'gaming',
    rating: 4.2,
    reviews: 56210,
    description: '7.1 surround sound gaming headset with LED illumination.',
    features: ['7.1 Surround Sound', 'RGB LED', 'Noise-cancelling mic', 'USB'],
    image: 'https://loremflickr.com/400/400/gaming,headset,headphones?lock=12',
  },
  {
    name: 'Ant Esports MK1300 Pro TKL Keyboard',
    brand: 'Ant Esports',
    price: 1799,
    category: 'gaming',
    rating: 4.4,
    reviews: 23410,
    description: 'Tenkeyless mechanical-feel gaming keyboard with RGB backlighting.',
    features: ['TKL layout', 'RGB backlit', 'Anti-ghosting', 'Multimedia keys'],
    image: 'https://loremflickr.com/400/400/gaming,keyboard,mechanical?lock=13',
  },
  {
    name: 'Redgear Bingo 750 Speed Gaming Mousepad',
    brand: 'Redgear',
    price: 499,
    category: 'gaming',
    rating: 4.3,
    reviews: 89210,
    description: 'Extended gaming mousepad with micro-textured surface for precise control.',
    features: ['750x300mm', 'Non-slip base', 'Smooth surface', 'Stitched edges'],
    image: 'https://loremflickr.com/400/400/mousepad,gaming,desk?lock=14',
  },
  {
    name: 'PowerA Enhanced Wired Controller',
    brand: 'PowerA',
    price: 2499,
    category: 'gaming',
    rating: 4.5,
    reviews: 12340,
    description: 'Xbox-compatible wired controller with mappable buttons.',
    features: ['Mappable buttons', '3m braided cable', 'Trigger locks', 'Rumble motors'],
    image: 'https://loremflickr.com/400/400/gamepad,controller,xbox?lock=15',
  },
  {
    name: 'Corsair HS35 Stereo Gaming Headset',
    brand: 'Corsair',
    price: 3499,
    category: 'gaming',
    rating: 4.6,
    reviews: 28470,
    description: 'Premium gaming headset with custom-tuned 50mm drivers.',
    features: ['50mm drivers', 'Detachable mic', 'Plush ear cushions', 'Multi-platform'],
    image: 'https://loremflickr.com/400/400/corsair,headset,gaming?lock=16',
  },
  {
    name: 'boAt Rockerz 510 Wireless Headphones',
    brand: 'boAt',
    price: 1299,
    category: 'gaming',
    rating: 4.2,
    reviews: 123410,
    description: 'Wireless over-ear headphones with 20hrs playtime and deep bass.',
    features: ['Bluetooth 5.0', '20hr battery', 'Deep bass', 'Built-in mic'],
    image: 'https://loremflickr.com/400/400/wireless,headphones,bluetooth?lock=17',
  },
  {
    name: 'GodMode GM-0031 Adjustable Gaming Chair',
    brand: 'GodMode',
    price: 7999,
    category: 'gaming',
    rating: 4.1,
    reviews: 8920,
    description: 'Ergonomic gaming chair with adjustable armrests and lumbar support.',
    features: ['Adjustable height', 'Lumbar support', '150° recline', 'PU leather'],
    image: 'https://loremflickr.com/400/400/gaming,chair,ergonomic?lock=18',
  },
 
  // ─── STUDY SETUP ─────────────────────────────────────────────
  {
    name: 'Classmate Long Size Notebook Pack of 6',
    brand: 'Classmate',
    price: 299,
    category: 'study',
    rating: 4.5,
    reviews: 123410,
    description: 'Pack of 6 ruled long-size notebooks, 200 pages each.',
    features: ['200 pages each', 'Ruled pages', 'Soft cover', 'Pack of 6'],
    image: 'https://loremflickr.com/400/400/notebook,diary,book,study?lock=19',
  },
  {
    name: 'Camlin Mathemagic Mathematical Instruments',
    brand: 'Camlin',
    price: 149,
    category: 'study',
    rating: 4.4,
    reviews: 89210,
    description: 'Comprehensive geometry set with compass, protractor, and ruler.',
    features: ['9-piece set', 'Stainless steel', 'Precision instruments', 'Carry case'],
    image: 'https://loremflickr.com/400/400/compass,geometry,ruler,math?lock=20',
  },
  {
    name: 'Staedtler Ball Pen Pack of 10',
    brand: 'Staedtler',
    price: 249,
    category: 'study',
    rating: 4.6,
    reviews: 156210,
    description: 'Smooth writing ball pens with comfortable grip, blue ink.',
    features: ['Smooth writing', 'Blue ink', 'Comfortable grip', 'Pack of 10'],
    image: 'https://loremflickr.com/400/400/pen,stationery,writing?lock=21',
  },
  {
    name: 'HP v150w 16GB USB Flash Drive',
    brand: 'HP',
    price: 349,
    category: 'study',
    rating: 4.2,
    reviews: 34210,
    description: 'Compact 16GB USB drive, ideal for storing notes and presentations.',
    features: ['16GB capacity', 'USB 2.0', 'Swivel design', 'Plug & Play'],
    image: 'https://loremflickr.com/400/400/usb,pendrive,flash,storage?lock=22',
  },
  {
    name: 'Portronics Mync Adjustable Laptop Stand',
    brand: 'Portronics',
    price: 999,
    category: 'study',
    rating: 4.3,
    reviews: 18230,
    description: 'Adjustable aluminum laptop stand with heat dissipation design.',
    features: ['Adjustable height', 'Aluminum build', 'Foldable', 'Non-slip'],
    image: 'https://loremflickr.com/400/400/laptop,stand,desk,aluminum?lock=23',
  },
  {
    name: 'Philips Mycare LED Desk Lamp',
    brand: 'Philips',
    price: 999,
    category: 'study',
    rating: 4.4,
    reviews: 23410,
    description: 'Eye-care LED desk lamp with 5 brightness levels and USB port.',
    features: ['5 brightness levels', 'USB charging port', 'Touch control', 'Eye-care LED'],
    image: 'https://loremflickr.com/400/400/lamp,desk,led,light?lock=24',
  },
  {
    name: 'Wildcraft Ace 25L Laptop Backpack',
    brand: 'Wildcraft',
    price: 1499,
    category: 'study',
    rating: 4.5,
    reviews: 45210,
    description: 'Water-resistant laptop backpack with padded compartment up to 15.6".',
    features: ['15.6" laptop slot', 'Water-resistant', 'USB charging port', '25L capacity'],
    image: 'https://loremflickr.com/400/400/backpack,bag,laptop,school?lock=25',
  },
  {
    name: 'Kindle Paperwhite 8GB E-Reader',
    brand: 'Amazon',
    price: 7999,
    category: 'study',
    rating: 4.7,
    reviews: 213410,
    description: '6.8" glare-free display, waterproof, with adjustable warm light.',
    features: ['6.8" display', 'Waterproof', 'Warm light', '10-week battery'],
    image: 'https://loremflickr.com/400/400/kindle,ebook,reader,tablet?lock=26',
  },
  {
    name: 'Casio FX-82MS Scientific Calculator',
    brand: 'Casio',
    price: 699,
    category: 'study',
    rating: 4.8,
    reviews: 189210,
    description: '240 functions, 2-line display, ideal for school and engineering.',
    features: ['240 functions', '2-line display', 'Solar + battery', 'Slide cover'],
    image: 'https://loremflickr.com/400/400/calculator,casio,math,science?lock=27',
  },
 
  // ─── FASHION ─────────────────────────────────────────────────
  {
    name: "U.S. Polo Assn. Men's Basic T-Shirt",
    brand: 'U.S. Polo Assn.',
    price: 699,
    category: 'fashion',
    rating: 4.3,
    reviews: 89210,
    description: 'Classic crew-neck cotton T-shirt, relaxed fit, multiple colors.',
    features: ['100% cotton', 'Crew neck', 'Regular fit', 'Machine washable'],
    image: 'https://loremflickr.com/400/400/tshirt,men,polo,fashion?lock=28',
  },
  {
    name: "Levi's 511 Slim Fit Jeans",
    brand: "Levi's",
    price: 2499,
    category: 'fashion',
    rating: 4.5,
    reviews: 56210,
    description: 'Iconic slim fit jeans with stretch fabric for all-day comfort.',
    features: ['Slim fit', 'Stretch fabric', 'All-day comfort', 'Multiple washes'],
    image: 'https://loremflickr.com/400/400/jeans,denim,fashion?lock=29',
  },
  {
    name: 'Puma Pacer Next Cage Sneakers',
    brand: 'Puma',
    price: 2999,
    category: 'fashion',
    rating: 4.4,
    reviews: 34210,
    description: 'Lightweight mesh sneakers with EVA midsole for cushioning.',
    features: ['Mesh upper', 'EVA midsole', 'Rubber outsole', 'Lace-up closure'],
    image: 'https://loremflickr.com/400/400/sneakers,shoes,sport?lock=30',
  },
  {
    name: 'Fastrack Quartz Analog Watch',
    brand: 'Fastrack',
    price: 1799,
    category: 'fashion',
    rating: 4.2,
    reviews: 123410,
    description: 'Casual analog watch with metal bracelet and water resistance.',
    features: ['Quartz movement', 'Metal bracelet', '50m water resistant', 'Mineral glass'],
    image: 'https://loremflickr.com/400/400/watch,analog,wristwatch?lock=31',
  },
  {
    name: "Campus Men's Running Shoes",
    brand: 'Campus',
    price: 1299,
    category: 'fashion',
    rating: 4.3,
    reviews: 45210,
    description: 'Lightweight running shoes with cushioned insole and breathable mesh.',
    features: ['Breathable mesh', 'Cushioned insole', 'Lightweight', 'Non-slip sole'],
    image: 'https://loremflickr.com/400/400/running,shoes,sport,footwear?lock=32',
  },
  {
    name: "Peter England Men's Formal Shirt",
    brand: 'Peter England',
    price: 899,
    category: 'fashion',
    rating: 4.2,
    reviews: 62310,
    description: 'Regular fit formal shirt in premium cotton-blend fabric.',
    features: ['Cotton-blend', 'Regular fit', 'Machine washable', 'Collar stays'],
    image: 'https://loremflickr.com/400/400/shirt,formal,men,fashion?lock=33',
  },
  {
    name: 'Wildcraft 35L Trekking Backpack',
    brand: 'Wildcraft',
    price: 2499,
    category: 'fashion',
    rating: 4.5,
    reviews: 23410,
    description: 'Ergonomic trekking bag with rain cover and multiple pockets.',
    features: ['35L capacity', 'Rain cover', 'Padded straps', 'Multiple pockets'],
    image: 'https://loremflickr.com/400/400/backpack,trekking,hiking,bag?lock=34',
  },
 
  // ─── KITCHEN ─────────────────────────────────────────────────
  {
    name: 'Milton Thermosteel 1L Insulated Bottle',
    brand: 'Milton',
    price: 699,
    category: 'kitchen',
    rating: 4.6,
    reviews: 213410,
    description: 'Double-wall insulated steel bottle keeps beverages hot/cold for 24hrs.',
    features: ['24hr insulation', 'Food-grade steel', 'Leak-proof', '1 litre'],
    image: 'https://loremflickr.com/400/400/bottle,steel,water,flask?lock=35',
  },
  {
    name: 'Cello Max Fresh Lunch Box Set',
    brand: 'Cello',
    price: 399,
    category: 'kitchen',
    rating: 4.4,
    reviews: 89210,
    description: '3-container plastic lunch box set with leak-proof lids.',
    features: ['3 containers', 'Leak-proof lids', 'Microwave safe', 'BPA free'],
    image: 'https://loremflickr.com/400/400/lunchbox,container,food,kitchen?lock=36',
  },
  {
    name: 'Prestige Deluxe Plus Pressure Cooker 3L',
    brand: 'Prestige',
    price: 1499,
    category: 'kitchen',
    rating: 4.5,
    reviews: 56210,
    description: 'Aluminum pressure cooker with safety valve and gasket release.',
    features: ['3 litre', 'Safety valve', 'Aluminium body', 'ISI certified'],
    image: 'https://loremflickr.com/400/400/pressure,cooker,kitchen,cooking?lock=37',
  },
  {
    name: 'Philips HL7756 Mixer Grinder 750W',
    brand: 'Philips',
    price: 3299,
    category: 'kitchen',
    rating: 4.4,
    reviews: 34210,
    description: '750W mixer grinder with 3 jars and anti-rust stainless steel blades.',
    features: ['750W motor', '3 jars', 'Stainless blades', '2 year warranty'],
    image: 'https://loremflickr.com/400/400/mixer,blender,grinder,kitchen?lock=38',
  },
  {
    name: 'Pigeon Rapido Cute 1200W Induction Cooktop',
    brand: 'Pigeon',
    price: 1799,
    category: 'kitchen',
    rating: 4.3,
    reviews: 45210,
    description: 'Portable induction cooktop with push-button controls and 7 preset menus.',
    features: ['1200W', '7 preset menus', 'Auto shut-off', 'LED display'],
    image: 'https://loremflickr.com/400/400/induction,cooktop,stove,kitchen?lock=39',
  },
  {
    name: 'Borosil Glass Mixing Bowl Set of 3',
    brand: 'Borosil',
    price: 799,
    category: 'kitchen',
    rating: 4.5,
    reviews: 62310,
    description: 'Borosilicate glass mixing bowls, microwave and dishwasher safe.',
    features: ['Borosilicate glass', 'Microwave safe', 'Dishwasher safe', 'Set of 3'],
    image: 'https://loremflickr.com/400/400/bowl,glass,kitchen,cooking?lock=40',
  },
  {
    name: 'Amazon Basics 20L Microwave Oven',
    brand: 'Amazon Basics',
    price: 6499,
    category: 'kitchen',
    rating: 4.2,
    reviews: 23410,
    description: '20L solo microwave with 5 power levels and defrost function.',
    features: ['20 litre', '5 power levels', 'Defrost mode', '1 year warranty'],
    image: 'https://loremflickr.com/400/400/microwave,oven,kitchen,appliance?lock=41',
  },
];
 
const seed = async () => {
  try {
    const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/cartiq';
    await mongoose.connect(MONGO_URI);
    console.log('✅ MongoDB connected');
 
    await Product.deleteMany({});
    console.log('🗑️  Old products cleared');
 
    const inserted = await Product.insertMany(products);
    console.log(`✅ Seeded ${inserted.length} products successfully`);
 
    await mongoose.disconnect();
    console.log('✅ Done! Run: npm run dev');
  } catch (err) {
    console.error('❌ Seed error:', err);
    process.exit(1);
  }
};
 
seed();